"""add redaction pipeline tables

Revision ID: 137dd7e18c85
Revises: 9c89a84af0d3
Create Date: 2026-07-14 02:46:37.865128

"""

import sqlalchemy as sa
import sqlmodel
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "137dd7e18c85"
down_revision = "9c89a84af0d3"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "page",
        sa.Column("document_id", sa.UUID(), nullable=False),
        sa.Column("page_number", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["document_id"], ["document.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("document_id", "page_number", name="uq_page_document_page_number"),
    )
    op.create_index(op.f("ix_page_created_at"), "page", ["created_at"], unique=False)
    op.create_index("ix_page_document_id", "page", ["document_id"], unique=False)
    op.create_table(
        "redaction_job",
        sa.Column("document_id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "UPLOADED",
                "INGESTED",
                "DETECTED",
                "IN_REVIEW",
                "APPLYING",
                "VERIFIED",
                "EXPORTED",
                "FAILED",
                name="job_status",
                native_enum=False,
            ),
            server_default="uploaded",
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["document_id"], ["document.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["organization_id"], ["organization.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("document_id"),
    )
    op.create_index(op.f("ix_redaction_job_created_at"), "redaction_job", ["created_at"], unique=False)
    op.create_index("ix_redaction_job_organization_id", "redaction_job", ["organization_id"], unique=False)
    op.create_table(
        "span",
        sa.Column("page_id", sa.UUID(), nullable=False),
        sa.Column("bboxes", postgresql.JSONB(astext_type=sa.Text()), server_default="[]", nullable=False),
        sa.Column("text", sqlmodel.sql.sqltypes.AutoString(), nullable=False),  # type: ignore[attr-defined]
        sa.Column("category", sqlmodel.sql.sqltypes.AutoString(), nullable=False),  # type: ignore[attr-defined]
        sa.Column(
            "source_tier",
            sa.Enum("TIER_1", "TIER_2", "TIER_3", "MANUAL", name="source_tier", native_enum=False),
            nullable=False,
        ),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["page_id"], ["page.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_span_created_at"), "span", ["created_at"], unique=False)
    op.create_index("ix_span_page_id", "span", ["page_id"], unique=False)
    op.create_table(
        "audit_entry",
        sa.Column("job_id", sa.UUID(), nullable=False),
        sa.Column("span_id", sa.UUID(), nullable=True),
        sa.Column("reviewer_id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column(
            "action",
            sa.Enum("APPROVED", "REJECTED", "EDITED", "MANUAL_SPAN_ADDED", name="audit_action", native_enum=False),
            nullable=False,
        ),
        sa.Column("category", sqlmodel.sql.sqltypes.AutoString(), nullable=False),  # type: ignore[attr-defined]
        sa.Column("text_hash", sqlmodel.sql.sqltypes.AutoString(), nullable=False),  # type: ignore[attr-defined]
        sa.Column("entry_hash", sqlmodel.sql.sqltypes.AutoString(), nullable=False),  # type: ignore[attr-defined]
        sa.Column("prev_hash", sqlmodel.sql.sqltypes.AutoString(), nullable=False),  # type: ignore[attr-defined]
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["job_id"], ["redaction_job.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["organization_id"], ["organization.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["reviewer_id"], ["app_user.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["span_id"], ["span.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("job_id", "sequence", name="uq_audit_entry_job_sequence"),
    )
    op.create_index(op.f("ix_audit_entry_created_at"), "audit_entry", ["created_at"], unique=False)
    op.create_index("ix_audit_entry_organization_id", "audit_entry", ["organization_id"], unique=False)
    op.create_index("ix_audit_entry_span_id", "audit_entry", ["span_id"], unique=False)
    op.create_table(
        "disposition",
        sa.Column("span_id", sa.UUID(), nullable=False),
        sa.Column(
            "action", sa.Enum("APPROVED", "REJECTED", name="disposition_action", native_enum=False), nullable=False
        ),
        sa.Column("reason", sqlmodel.sql.sqltypes.AutoString(), nullable=True),  # type: ignore[attr-defined]
        sa.Column("reviewer_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["reviewer_id"], ["app_user.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["span_id"], ["span.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("span_id"),
    )
    op.create_index(op.f("ix_disposition_created_at"), "disposition", ["created_at"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_disposition_created_at"), table_name="disposition")
    op.drop_table("disposition")
    op.drop_index("ix_audit_entry_span_id", table_name="audit_entry")
    op.drop_index("ix_audit_entry_organization_id", table_name="audit_entry")
    op.drop_index(op.f("ix_audit_entry_created_at"), table_name="audit_entry")
    op.drop_table("audit_entry")
    op.drop_index("ix_span_page_id", table_name="span")
    op.drop_index(op.f("ix_span_created_at"), table_name="span")
    op.drop_table("span")
    op.drop_index("ix_redaction_job_organization_id", table_name="redaction_job")
    op.drop_index(op.f("ix_redaction_job_created_at"), table_name="redaction_job")
    op.drop_table("redaction_job")
    op.drop_index("ix_page_document_id", table_name="page")
    op.drop_index(op.f("ix_page_created_at"), table_name="page")
    op.drop_table("page")
    # ### end Alembic commands ###
