"""add redacted_pdf_key to redaction_job

Revision ID: dbbf5c84e9b6
Revises: 137dd7e18c85
Create Date: 2026-07-14 18:13:06.400431

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'dbbf5c84e9b6'
down_revision = '137dd7e18c85'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('redaction_job', sa.Column('redacted_pdf_key', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('redaction_job', 'redacted_pdf_key')
    # ### end Alembic commands ###
